<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hovercraft">

    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="body_width" value="0.3" /> 
    <xacro:property name="body_length" value="0.4" />
    <xacro:property name="body_height" value="0.1" />

    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_width" value="0.04" />

    <material name="blue"><color rgba="0.2 0.2 0.8 1"/></material>
    <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
    <material name="white"><color rgba="1 1 1 1"/></material>

    <link name="base_link">
        <visual>
            <geometry><box size="${body_length} ${body_width} ${body_height}"/></geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry><box size="${body_length} ${body_width} ${body_height}"/></geometry>
        </collision>
        <inertial>
            <mass value="5"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
        </inertial>
    </link>

    <link name="right_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
            <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
            <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="left_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
            <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
            <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
    </link>

    <link name="camera_link">
        <visual><geometry><box size="0.05 0.05 0.05"/></geometry><material name="white"/></visual>
        <collision><geometry><box size="0.05 0.05 0.05"/></geometry></collision>
        <inertial><mass value="0.1" /><inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" /></inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 -${body_width/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${body_width/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${body_length/2} 0 ${body_height/2}" rpy="0 0 0"/>
    </joint>

    <transmission name="right_wheel_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_wheel_actuator">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="left_wheel_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_wheel_actuator">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


    <gazebo>
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${body_width}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <torque>10</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
    </gazebo>

    <gazebo reference="camera_link">
        <sensor type="camera" name="camera_sensor">
            <update_rate>30.0</update_rate>
            <camera>
                <horizontal_fov>1.396</horizontal_fov>
                <image><width>800</width><height>800</height></image>
                <clip><near>0.02</near><far>300</far></clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <cameraName>hovercraft/camera</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

</robot>